### ISSUE TITLE
Text Box Enhancements

### ISSUE THREAD

**Issue by shakirm** [deep-learning-indaba/Baobab#132]
Can the text boxes be enhanced to include some of the following

- To turn red around the box, as soon as the word count is exceeded rather than waiting for the button for next to be pressed to change it.

- Can this text area be made richer: allowing for hyperlinks, bullets, bold and italic fonts, indents (much like this text box for the github issues).

**Comment by avishkar58** [comment]
potential solution: https://github.com/andrerpena/react-mde

**Comment by avishkar58** [comment]
Hey @NileshArnaiya , this one is still relevant if you want to continue with it. The place to start here would be adding a `FormRichText` control to `webapp/src/components/form`

**Comment by NileshArnaiya** [comment]
I'm familiar with draftJS, more like this - https://jpuri.github.io/react-draft-wysiwyg/

**Comment by avishkar58** [comment]
Sure, whatever you think is best, as long as it has decent browser support (at least as good as React itself) and can save in Markdown.

**Comment by avishkar58** [comment]
Oh and mobile friendly :)

**Comment by NileshArnaiya** [comment]
Copy pasted functions from FormTextArea, The problem is with the validation part of the FormRichText which needs to be the same as FormTextArea so I tried using the same functions from FormTextArea in FormRichText but it won't work as I'm using draftjs and editorstate works differently and maybe I don't completely understand how ApplicationForm uses FormTextArea I tried replacing it with richText and word count and everything is fine but no validation.
