### ISSUE TITLE
Better documentation on running the app locally for development

### ISSUE THREAD

**Issue by arunavkonwar** [deep-learning-indaba/Baobab#24]
The documentation can be a bit clearer on how to get the whole app up and running. A few more intermediate steps can be really useful.

**Comment by arunavkonwar** [comment]
@avishkar58 I personally was able to clone the project to my local machine and install `docker` and `docker-compose`. Beyond that, I found it confusing where to go. The `docker-compose build` and `docker-compose up` commands threw up a bunch of errors (since it was the next command written in the documentation). I gave up there due to the lack of information to proceed.

I feel we can improve this if we can include even the seemingly basic steps to make the project even more inclusive. Right from the commands for **git cloning the project** to links to relevant docker installations. Basically the **linear steps** you'd need to take to get the project up and running. 

Also, I'd also love to see platform specific (Windows/Linux/Mac) build instructions if any.

Maybe we can take something like [this](https://github.com/processing/processing/wiki/Build-Instructions) as a template to make the whole process a bit clearer.

Thanks :)

**Comment by avishkar58** [comment]
Thanks, I've updated the README with some more details, will keep iterating on this in the coming days, using the link you sent as inspiration. Please let us know what errors you got, as others may be facing the same or similar issues?

**Comment by knaggita** [comment]
I managed to install docker on my machine, clone the repo and run the app.

I have a few suggestions to the modification of the contribution page

**A few suggestions on step 5**

If you successfully installed docker on your machine and can run the hello world application with the command "docker run hello-world". Then 

Navigate to the project repository. "cd Baobab"

Build the containers using "docker-compose build" - this will build the front-end, back-end, and database together. It will take a fair bit of time the first time you do it, subsequently, it will be much faster! 

If you get an error about apt-get update -qq, run "curl -sSL https://get.docker.com/ | sh" and then rerun the "docker-compose build" command.

If you get any more errors at this step, please get in touch!

**And few suggestions and corrections Step 7:**

Highlight  **another terminal/command prompt:**  in the step because I am certain a lot of people will miss it.

I think it should be "docker-compose run web python ./api/run.py db upgrade --directory api/migrations" since run.py is in api folder which is on the root of the Baobab folder.

`

**Comment by avishkar58** [comment]
Thanks @knaggita! - I've incorporated your suggestions

**Comment by avishkar58** [comment]
Closing this following a number of improvements to the docs. Please open new bugs if there are any more issues or areas we can improve on.
