### ISSUE TITLE
Update File API in front-end

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#443]
Update the File Upload Component (webapp/src/components/form/FormFileUpload.js) to use the new file api developed in #442 

Depends on #442

Check if there are any other places in the front-end where we query the old file API and update it to use the new one.

**Comment by arunavkonwar** [comment]
Hi, I wanted to take this issue up, but I realized that things have moved around a bit since I was last here. Can you clarify how to log into the site in the development mode? I got everything up and running and just couldn't log in. Thanks :)

**Comment by avishkar58** [comment]
Hey Arunav,
There is no default user in development mode, so you can just sign up a new
user on your instance
Thanks for helping! :)

**Comment by amritpurshotam** [comment]
@avishkar58 What's the urgency on this issue? #442 is finished now (#549) but I figured this needs to be done in the same branch since changing the file upload will be broken now on the front end and the fetching of the files needs to be updated as well. Also when updating the fetching of the files, how are we going to differentiate ones that were uploaded before we had the file table and ones after?

**Comment by avishkar58** [comment]
Hold until #442 is done
