### ISSUE TITLE
Add privacy policy agreed date to AppUser

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#488]
The follow changes are required for GDPR compliance.

Add a new field called policy_agreed_date to the AppUser model (api/app/users/models.py).

Create a migration to apply the above change to the database 

Update the User API (api/app/users/api.py) post methods to set the policy_agreed_date to the current date when creating a new user 

Create a new PrivacyPolicyAPI with a put method that updates the policy_agreed_date to the current date for the logged in user.

**Comment by nlauchande** [comment]
Couldn't find any other unnassigned backend issues wonder if I can try my luck on getting started contributing on this one?

**Comment by amritpurshotam** [comment]
@nlauchande Thanks for helping out! It looks you don't have access to the repo yet though. Could you please fill out this form to grant it? It helps us keep track of the contributors and their skills so we know who to turn to in case we need it :) https://docs.google.com/forms/d/e/1FAIpQLSee_7ID0N-fvdE3owDpoIJ69PDcGFrpbClbxusxLU2bj58BYw/viewform
We also prefer to not have contributors work on forks since our CircleCI tests don't run on the other repos.
