### ISSUE TITLE
Check status logic on EventHome

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#505]
There is some fairly complicated logic on EventHome.js to determine the correct status to display to the user based on a number of different states they could be in: For example, whether they've applied, been accepted, withdrew their application, rejected their offer, are an invited guest etc. Go through and document this logic and look for any cases that we're not covering. Improve the code by moving the status logic to a function and simplify it as much as possible.

**Comment by avishkar58** [comment]
This is good for front-end newcomers because it's more about understanding and improving the existing mostly Javascript logic, rather than fiddling with React :)

**Comment by wpumacay** [comment]
Hi @avishkar58 , I think I could help with this one. Is there a way to go to the event-home page directly (without going through the process of filling a form)?. I was trying to work on #467 , but didn't know how to test it either  :sweat_smile:  . I've already setup everything and have the webapp running as expected (although only the "Upcoming events" message is shown, which is weird as last week there were options to fill applications, etc.). I'm currently at a571f1a139d6f1820117eae746dbc47f9bfbb566, perhaps there were some changes in **dev** that I'm not aware of since e7aad3a63237be5f16e6441b89b3cc708ec19acd.
