### ISSUE TITLE
Form accepts whitespaces as valid input

### ISSUE THREAD

**Issue by SMHall94** [deep-learning-indaba/Baobab#535]
![image](https://user-images.githubusercontent.com/43542098/73930611-7bca8c00-48df-11ea-9f82-b3df698cad05.png)

- Possible loophole for certain important information to not be included

**Comment by avishkar58** [comment]
Hey @SMHall94 - was this for the Affiliation question? If so, it would accept spaces or complete blanks because it's not a required field :)  See [here](https://docs.google.com/document/d/1ZOL4E3sQCS8vCCHCLKQZUWwPHpepxW1NHQyPRWnr6kQ/edit#) for more information. The only required text box is the "Research Interests" one, so it would be problematic if that accepted spaces as characters!
