### ISSUE TITLE
Update Event model to support translation

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#719]
Update the [event model](https://github.com/deep-learning-indaba/Baobab/blob/597eec3fd31a606b47ca82a7911fb01930fc5e08/api/app/events/models.py#L12) by splitting it into two models, `Event` and `EventTranslation` with a one-to-many relationship. Move the `name` and `description` fields to the `EventTranslation` model and add an additional `language` parameter to `EventTranslation` which will contain the 2-character (ISO 639-1) language code.

Update the [EventsAPI](https://github.com/deep-learning-indaba/Baobab/blob/597eec3fd31a606b47ca82a7911fb01930fc5e08/api/app/events/api.py#L313) and [EventsByKeyAPI](https://github.com/deep-learning-indaba/Baobab/blob/597eec3fd31a606b47ca82a7911fb01930fc5e08/api/app/events/api.py#L418) get methods to use the language query parameter passed from the front-end (see #718, default this parameter to "en" if #718 hasn't landed yet) to select the correct translation for the `name` and `description` fields. NOTE: The JSON returned to the front-end shouldn't change - it should just contain the correct language in the `name` and `description` fields.

Update the [EventAPI](https://github.com/deep-learning-indaba/Baobab/blob/597eec3fd31a606b47ca82a7911fb01930fc5e08/api/app/events/api.py#L151) get method to return a dictionary for the `name` and `description` properties where the key is the language code and the value is the translation in that language for the relevant property. For example, the JSON returned by the EventAPI get method should look something like this:

```
{
  "id": 1,
  "name": {
     "en": "Innovation Grants",
     "fr": "subvention à l'innovation"
  },
  "description": {
    "en": "This is an English description",
    "fr": "Ceci est une description française"
  },
  "key": "blah2020",
  ...
}
```

Update the POST and PUT methods to accept incoming JSONs of the form above and insert/update records in the EventTranslation for each language.

See the [multi-language design doc](https://docs.google.com/document/d/1PktZq6kepUCQjatvDUj_-mgwm_YgUHNN5Gyg2lDzz4A/edit?ts=5f1601a4#) for more context

**Comment by avishkar58** [comment]
Hi @amritpurshotam  -  just checking how this is coming along? Keen to see your solution so I can copy it for the application form / other APIs :joy:

**Comment by amritpurshotam** [comment]
Haha yeah it is coming along. I was spending time going through the code base trying to figure out the best way of abstracting away the fact that there's translations.
I think what I've settled on is to add methods for fetching the name and description of the event with a language parameter from the event object so something like this

```
event.get_name(language):
    # logic to go through self.event_translations
    # return translated_name
```
And then the same for the descriptions. I was also looking to see how to lazy load just the one specific translation instead of all the translations in `self.event_translations` in the `Event` class. I know the other option is to just fetch the event translation in a repo method by `event_id` and `language` but I really want to encapsulate the logic in the `Event` class so the underlying translation structure is hidden away. 

So yeah I think by tonight I should have at least the initial working solution ready but probably by tomorrow I'll have all the tests done (and I want to add tests for the first time for the `EventAPI` since I think there's also possibly a bug there currently too)

**Comment by amritpurshotam** [comment]
@avishkar58 Didn't quite get to where I wanted to but got all the GET methods done. Still have the tests outstanding (but did eyeball the responses in Postman so confident it's working) and still need to do the PUT and POST but I think there's enough to go on in the draft PR to see how I'm going about fetching the translations. It's basically what I described above.

I think the key difference to how we've setup the child properties is that now the `event_translations` property is a [Query object by setting](https://docs.sqlalchemy.org/en/13/orm/collections.html#dynamic-relationship) `lazy='dynamic'`
`event_translations = db.relationship('EventTranslation', lazy='dynamic')`

And then we can efficiently retrieve just the language we want like so
```
def get_name(self, language):
        event_translation = self.event_translations.filter_by(language=language).first()
        if not None:
            return event_translation.name
        return None
```
