### ISSUE TITLE
Create Response page and component

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#781]
## Motivation
As part of the review improvements in Baobab, we want event admins to be able to see the responses to their event's application form. In issue #779 we create a list of key information from the responses, clicking on one of those should lead to a details page which shows all the details of the response. In later issues, we will add some additional functionality to this page (like adding tags, updating metadata etc) 

## Dependencies
Depends on the backend APIs created in #776 but can be implemented using mock data

## Requirements
- Create a new page accessible through the route /response/:id and a component that implements the functionality below
- Use the [Application Form Service](https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/src/services/applicationForm/applicationForm.service.js) to get the application form for the current event
- Create a service to interact with the API in #776, which passes a JSON request like the example below and gets back a response like the example below. Return dummy data if #776 has not been completed yet
- Using the application form as the structure, display the answers to the questions in the application form. This should display section names as headings, followed by the questions in order. The value displayed for each answer should depend on the question type.
  - Look at the [Confirmation component](https://github.com/deep-learning-indaba/Baobab/blob/d57978b2e55719ea82f2c6e416b5d97994265b5e/webapp/src/pages/applicationForm/components/ApplicationForm.js#L524) in ApplicationForm.js to see how sections, questions and answers should be displayed and how to display answers for the different question types
- Add a button/icon that allows the user to navigate back to the response list.
- Add tests for the new functionality

## Example JSON Request to the API
```
{
  "response_id": 2,
  "event_id": 1
}
```

## Example JSON Response from API
```
"id": 1,
"application_form_id": 1,
"user_id": 34,
"is_submitted": true,
"submitted_timestamp": "2020-06-02 [...]",    // ISO8601 Format
"is_withdrawn": false,
"withdrawn_timestamp": null,
"started_timestamp": "2020-06-02 [...]",    // ISO8601 Format
"user_title": "Ms",
"firstname": "Jane",
"lastname": "Bloggs",
"answers": [
  {"id": 4, "question_id": 1, "value": "First answer"},
  {"id": 5, "question_id": 2, "value": "Second answer"}
]
"language": "en"
```

**Comment by avishkar58** [comment]
Hi @greeffjean - in keeping with the responses theme, can you please implement this feature

**Comment by greeffjean** [comment]
Hi Avishkar.

Just two things: 

1. "Use the Application Form Service to get the application form for the current event
" - Here in the service functions parameters are required specifically an eventId, how would I go about mocking an eventId? 

2. This query may be linked to the one above, I have not actually had time yet today to study this query myself, before I do that perhaps you can just give me some background regarding eventKey's and React Routing, for instance if I go to "/responsePage/:Id" and I make something up I would get ""No event exists with that KEY".

**Comment by greeffjean** [comment]
If you could get back to above query today that would be great

**Comment by avishkar58** [comment]
Hi Jean,

So there are two sets of pages/routes in the application, one is at Organisation level and this includes pages like Login, Signup, User profile etc. The other is at the Event level and includes anything to do with application forms, responses etc. The organisation level routes are set up in [App.js](https://github.com/deep-learning-indaba/Baobab/blob/6c9b8d4d2051273ca23493d7012b18710f6f0839/webapp/src/App.js#L393). You'll notice the last route here has a path of `path="/:eventKey"` and points to the EventHome component. EventHome.js in turn defines the event level routes [here](https://github.com/deep-learning-indaba/Baobab/blob/6c9b8d4d2051273ca23493d7012b18710f6f0839/webapp/src/pages/eventHome/EventHome.js#L124). For this page, the route should be something like test2021/response/5   (where test2021 is the eventKey, response is the page, 5 is the response ID)

EventHome also takes care of matching the eventKey to the Event object and passes it as a property to the relevant component, so to get the event ID that you need for the application form service you can just use `this.props.event.id`

**Comment by avishkar58** [comment]
(Btw, you already set up the routing correctly for the ResponseList, so I thought you understood this already? so I think maybe I didn't quite understand your question? Please let me know if you need more info)

**Comment by greeffjean** [comment]
**Hi Avishkar**
_Below is the reponse I received from the Application form service, Im finding question and answerer matching quote complex, Im sure its due to a lack of understanding, this is also very different to the previous component Response List I built, can you please give me clarity on how Im supposed to match the output you see below with the mock data provided in the brief above_

`event_id: 3
id: 3
is_open: true
nominations: false
sections: Array(5)
0:
depends_on_question_id: null
description: "This is the official application form to apply for participation in the Deep Learning Indaba to be held 25-31 August 2019 in Nairobi, Kenya. Students can also use this application form to apply for travel and accommodation awards. ↵ ↵ ↵ Closing date: 30 April 2019"
id: 12
name: "Indaba 2019 Application Form"
order: 1
questions: []
show_for_values: null
__proto__: Object
1:
depends_on_question_id: null
description: "Please use this section to tell us a bit more about yourself and your intentions as a future Deep Learning Indaba ambassador."
id: 13
name: "Tell Us a Bit About You"
order: 2
questions: Array(7)
0:
depends_on_question_id: null
description: "Provide a paragraph of 50-150 words."
headline: "Why is attending the Deep Learning Indaba 2019 important to you?"
id: 37
is_required: true
key: null
options: null
order: 1
placeholder: "Enter 50 to 150 words"
show_for_values: null
type: "long_text"
validation_regex: "^\W*(\w+(\W+|$)){50,150}$"
validation_text: null
__proto__: Object
1:
depends_on_question_id: null
description: "Provide a paragraph of 50-150 words."
headline: "How will you share what you have learnt after the Indaba?"
id: 38
is_required: true
key: null
options: null
order: 2
placeholder: "Enter 50 to 150 words"
show_for_values: null
type: "long_text"
validation_regex: "^\W*(\w+(\W+|$)){50,150}$"
validation_text: null
__proto__: Object
2: {depends_on_question_id: null, description: "Maximum 80 words.", headline: "Share with us a favourite machine learning resourc…post, algorithm, result, or finding. Tell us why.", id: 39, is_required: true, …}
3: {depends_on_question_id: null, description: "Maximum 80 words.", headline: "Are you or have you been a tutor for any relevant … science society or meetup? If yes, give details.", id: 40, is_required: true, …}
4: {depends_on_question_id: null, description: "Maximum 150 words.", headline: "Have you worked on a project that uses machine learning? If yes, give a short description.", id: 41, is_required: false, …}
5: {depends_on_question_id: null, description: "We generally do not look at CVs, but ask for this …we can make a more informed selection, if needed.", headline: "Please upload your CV (pdf, max size 10MB)", id: 36, is_required: false, …}
6: {depends_on_question_id: null, description: "If you are accepted, we would like to add your CV …ormation from your application will be included).", headline: "May we add your CV and email address to a database for sharing with our sponsors?", id: 48, is_required: true, …}
length: 7
__proto__: Array(0)
show_for_values: null
__proto__: Object
2:
depends_on_question_id: null
description: "We may be able to sponsor the cost of travel and accommodation for some attendees. These travel awards are limited and highly competitive, but are assessed independently of Indaba attendance: applying for a travel award neither enhances nor undermines your chances of being accepted. To help as many people attend as possible, before applying for travel support, please check if your supervisor, department or university is able to support you in any way. "
id: 14
name: "Apply For Travel Support "
order: 3
questions: Array(5)
0: {depends_on_question_id: null, description: "Travel awards will be used to cover the costs of r…modation in shared dorm rooms close to the venue.", headline: "Would you like to be considered for a travel award?", id: 44, is_required: true, …}
1: {depends_on_question_id: null, description: "Maximum 150 words.", headline: "If you selected yes, please provide a short motiva… why you should be considered for a travel award.", id: 42, is_required: false, …}
2: {depends_on_question_id: null, description: null, headline: "If you selected yes to an award including transport, please state the intended airport of departure.", id: 43, is_required: false, …}
3: {depends_on_question_id: null, description: null, headline: "If you do not receive a travel award from us, will you still be able to attend?", id: 45, is_required: false, …}
4: {depends_on_question_id: null, description: "Please fill this in if you are applying for travel…ur South African sponsors for reporting purposes.", headline: "You Ethnicity (South African applicants only)", id: 49, is_required: false, …}
length: 5
__proto__: Array(0)
show_for_values: null
__proto__: Object
3:
depends_on_question_id: null
description: "Help us quantify our progress by giving us some info on your previous Indaba experiences."
id: 15
name: "Previous Attendance"
order: 5
questions: Array(2)
0: {depends_on_question_id: null, description: null, headline: "Did you attend the 2017 or 2018 Indaba", id: 46, is_required: true, …}
1: {depends_on_question_id: null, description: "Maximum 150 words.", headline: "If you attended a previous Indaba, tell us how it …u grow or how you have used what you have learnt.", id: 47, is_required: false, …}
length: 2
__proto__: Array(0)
show_for_values: null
__proto__: Object
4:
depends_on_question_id: null
description: "Anything else you may want us to know"
id: 16
name: "Additional Information"
order: 6
questions: Array(2)
0: {depends_on_question_id: null, description: "Maximum 150 words.", headline: "Any additional comments or remarks for the selection committee?", id: 50, is_required: false, …}
1: {depends_on_question_id: null, description: "Maximum 150 words.", headline: "Anything else you think relevant, for example link…repositories, community and outreach activities. ", id: 51, is_required: false, …}
length: 2
__proto__: Array(0)
show_for_values: null
__proto__: Object
length: 5
__proto__: Array(0)
__proto__: Object`

**Comment by avishkar58** [comment]
Hi Jean,

So the response from the application form service gives you the structure of how everything should be displayed and then you'd use the values from the ResponseDetail mock above to fill in values at the appropriate places. In terms of the structure: An Application Form consists of multiple Sections, a Section in turn consists of multiple Questions. So you'll need to:
- Loop through the sections, for each `section`:
  - Add `section.name` as a heading
  - Loop through the `section.questions` and for each `question`:
    - Add `question.headline` as a smaller heading
    - Look in the `answers` list that you got from the ResponseDetail mock data and see if any of the `answer.question_id` matches the `question.id` - this means that `answer` is the candidate's answer to that particular question on the application form. Display the `answer.value` according to the `question.type` similar to what you did in the ResponseList or the [AnswerValue](https://github.com/deep-learning-indaba/Baobab/blob/c9cb40b7eb16216b02aa1d32a5da031696023125/webapp/src/pages/applicationForm/components/ApplicationForm.js#L467) from ApplicationForm.js

Overall, the page should look similar to the Confirmation page that you get when you finish filling in an application form, but of course without the "Review your Answers [...]" text or the submit button. Instead, please display the properties from the ResponseDetail like `user_id`, `user_title`, `firstname`, `lastname` and also a some indicator of the **state** of the response, which can be one of three:
- unsubmitted (which means `is_submitted == false` and `is_withdrawn == false`) - then please display the `started_timestamp`
- submitted ( `is_submitted == true` ) - then please display the `submitted_timestamp`
- withdrawn ( `is_withdrawn == true` ) - then please display the `withdrawn_timestamp`

There are a few other small details, but to avoid causing confusion I'll explain those after you've got the bulk of it working! 

Hope this helps
