### ISSUE TITLE
Add more logging/audit to form responses

### ISSUE THREAD

**Issue by avishkar58** [deep-learning-indaba/Baobab#922]
At the moment it's not possible to see when someone edits the responses to an application or review form. Add some form of audit trail that will allow us to see what happened to a form - this will help diagnose issues that users report. 
- Ideally we would want to store a full copy of every edit that's made to a response eg by introducing versioning to the Response/ReviewResponse/RegistrationResponse tables.
- At the very least we should store the timestamps of every edit somewhere.

**Comment by bdhobare** [comment]
Hi @avishkar58 , is this task claimed? If not, I would love to claim it :)

**Comment by avishkar58** [comment]
Hi @bdhobare ! This hasn't been claimed, please feel free to assign it to yourself :) Let me know if you need any more information

**Comment by avishkar58** [comment]
@bdhobare if you do take this issue, please write a description of how you intend to solve it so that we can ensure we're all on the same page before you start writing code :)

**Comment by bdhobare** [comment]
Hello @avishkar58 
To minimize modifications to the API code, I believe using a `TRIGGER` function would be the fastest way to have an audit trail. The function would be executed for updates to the columns of interest.
### Example using `registration_answer` table
1.  Create an audit trail table:
```
DROP TABLE IF EXISTS registration_answer_audit;
CREATE TABLE  registration_answer_audit(
    id SERIAL,
    registration_answer_id INT NOT NULL,
    value VARCHAR,
    changed_on TIMESTAMP NOT NULL,
    PRIMARY KEY(id)
);
```
2. Create a migration to create a PL/PGSQL function:
```
CREATE OR REPLACE FUNCTION log_registration_answer_changes()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS
$$
BEGIN
    IF NEW.value <> OLD.value THEN
        INSERT INTO registration_answer_audit(registration_answer_id, value, changed_on)
        VALUES(OLD.id, OLD.value, NOW());
    END IF;
    RETURN NEW;
END;
$$
```
2. Create a trigger to attach this function to the  `registration_answer` table:
```
CREATE TRIGGER registration_answer_changes
    BEFORE UPDATE
    ON registration_answer
    FOR EACH ROW
    EXECUTE PROCEDURE log_registration_answer_changes();
```
3. Now for every UPDATE to the `value` column we log the changed value to `registration_answer_audit`  table:
```
UPDATE registration_answer SET value = 'Modified first answer' WHERE id = 2;
UPDATE registration_answer SET value = 'Modified again first answer' WHERE id = 2;
```
4. In the `downgrade` method of the migration, we delete the trigger and function:
```
DROP TRIGGER IF EXISTS registration_answer_changes ON registration_answer CASCADE;
DROP FUNCTION IF EXISTS log_registration_answer_changes();
```
## Pros of this approach
- No modification of the API code
- No managing of transactions manually if we were to manually update two table for each update.
- Ensures audit integrity because the flow is handled by the DB engine.
## Cons
- The audit table might grow large depending on the number of edits the users are doing. We can mitigate this by limiting number of edits stored to the past <5 edits.

**Comment by amritpurshotam** [comment]
Hello @bdhobare, @avishkar58 asked me to also have a look over to see if we're covering all the _response_ type tables.
I noticed we were missing the `guest_registration_answer` table so I think include that one as well (@avishkar58 can you confirm? not sure if this one has been problematic as well)

@bdhobare And in case this saves time (since I think you might have already figured this out by looking at the schema closely), the tables that should be logged instead
 - `answer` instead of `response`
 - `review_score` instead of `review_response`

`response` and `review_response` have timestamp, boolean, and foreign key fields which probably aren't going to change but `answer` and `review_score` are their child tables respectively and contain the `value` column that we care more about (so very similar to the `registration_answer` table). 

Otherwise yeah I do like this approach especially side stepping having to make code changes.

**Comment by avishkar58** [comment]
Hi @bdhobare ,

Thanks for sharing your proposed solution and apologies for the delay in responding! 
I appreciate your pragmatic approach to solving this and the desire to minimise code changes and the resulting risk of disruption. However, I do see a few more cons with this approach, in particular:
- Triggers are inconsistent wit the "model first" approach followed by the rest of the system
- The logic is hidden to future contributors who work on the assumption that everything is contained in the models and repositories
- The trigger logic is not unit testable in our current framework, nor will the triggers exist when unit testing (because we create a test database from scratch in SQLLite every time we run unit tests, directly from the model) 

Based on the above and after some further discussion with @amritpurshotam , we think that the best approach would be the versioning approach. This could be achieved fairly simply by adding an Active flag to each of the Response/ReviewResponse/RegistrationResponse tables. This can be set to True by default in the constructors of those objects to minimise the number of places this needs to be propagated. Then the PUT methods in the APIs would need to be changed to set Active to False on previous records and insert a new record (instead of updating the existing record). Finally the repositories would need to be changed to filter on `Active = True` whenever querying these tables.

I do think that since we have spent a lot of effort writing good unit tests for our APIs, that we shouldn't shy away from changing them when necessary. This approach also has the advantage that it would be easier to add an "edit history" feature in the future. 

Hope you haven't made too much progress on writing code for this already and that this change in approach doesn't cause too much disruption! Also happy to point out code locations that would need to change if that would be useful?

Thanks!

**Comment by bdhobare** [comment]
Hi @avishkar58 , thanks for replying and your points. They do make sense. I had not written any significant code apart from just studying the current schema. I will work on this recommended changes and send a fix.

**Comment by avishkar58** [comment]
Fantastic thanks Miles! Please let me know if you need any more information
